### ISSUE TITLE
Remove stats profiling in favor of prometheus

### ISSUE THREAD

**Issue by epociask** [Layr-Labs/eigenda-proxy#113]

**Comment by samlaf** [comment]
Update here after chatting with @epociask: seems like prometheus doesn't make it easy to Get the value of some counter/gauge (unlike VictoriaMetrics, see [here](https://stackoverflow.com/a/71945912/4971151)). Furthermore the way they propose (using https://github.com/prometheus/client_model) is deprecated... so not sure what's the recommended way to do this in 2024.

Another way is to use some internal atomic variable, which we increment and use in code, and then wrap that and expose it to prometheus via a CounterFunc (see [here](https://stackoverflow.com/a/57963829/4971151)).
