### ISSUE TITLE
eigenda flags don't use same syntax as other flags

### ISSUE THREAD

**Issue by samlaf** [Layr-Labs/eigenda-proxy#143]
Should we change the eigenda flags to use `.` instead of `-`: `eigenda.<FLAG_NAME>` instead of `eigenda-<FLAG_NAME`, like we do for all the other subsystem flags?
<img width="799" alt="image" src="https://github.com/user-attachments/assets/44f6c9a1-f2c8-4585-af3e-4a7319b6c337">

**Comment by epociask** [comment]
closed by https://github.com/Layr-Labs/eigenda-proxy/pull/146
