### ISSUE TITLE
Rename SIGNER_PRIVATE_KEY to AUTHZ_PRIVATE_KEY ?

### ISSUE THREAD

**Issue by samlaf** [Layr-Labs/eigenda-proxy#162]
Should we rename [SIGNER_PRIVATE_KEY_HEX](https://github.com/Layr-Labs/eigenda-proxy/blob/35885817ac8195fa6560ff8274238297473341e8/flags/eigendaflags/cli.go#L81) flag to something else? Perhaps this needs to be done in the eigenda-client itself beforehand?

Personally find the name weird because everytime I think that it needs to be a funded private key, but actually this is just the private key that is used for rate limiting on the eigenda disperser right?

**Comment by samlaf** [comment]
cc @bxue-l2 @epociask

**Comment by bxue-l2** [comment]
no objection, would sometime like EIGENDA_DISPERSAL_ACCOUNT_PRIVATE_KEY_HEX be better?

**Comment by samlaf** [comment]
Sgtm

**Comment by epociask** [comment]
@samlaf the only consideration I have if there's an intended use for this key with our payments model. otherwise fully agree

**Comment by epociask** [comment]
cc @hopeyen

**Comment by hopeyen** [comment]
EigenDA client would use a funded key to sign over payment information and construct blob request header (maybe unfunded is okay, if we register something like an operator key mapped to a funded account on-chain). Without payments, this key is eventually used to [sign](https://github.com/Layr-Labs/eigenda/blob/003c358465799acb4d44726e60e64e24471a0c08/core/auth/signer.go#L34) over blob headers which makes `SIGNER_` an okay name imo. Though `AUTHZ_` is also fine, am not opinionated at all

**Comment by samlaf** [comment]
Ah good points. I’m that case we can keep it with this name, but let’s add better documentation and that should do it.
