### ISSUE TITLE
Fault/fraud testing

### ISSUE THREAD

**Issue by epociask** [Layr-Labs/eigenda-proxy#21]
Clients can provide optional role IDs (e.g, `sequencer`, `defensive_validator`) which the server can process for role specific interaction behaviors. 

## Interaction Behavior Types
- `honest`: server returns proper batches associated with a commitment 
- `interval_dishonesty`: server returns a malformed batch every `x` calls for some client role
- `dishonest`: server continuously lies and returns batches that are irrespective of the actual commitment 

## Representation
A json rep can be used to define the expected return behavior for the proxy server; e.g:
```
{
    "sequencer": {
        "mode": "interval_dishonesty",
        "interval": 10,
    },
    "defensive_validator": {
        "mode": "honest"
    },
}

```

**Comment by teddyknox** [comment]
This is good, my only comment is that it should be named something testing specific like "fault-test-mode".
