### ISSUE TITLE
Support redis backend for memstore

### ISSUE THREAD

**Issue by epociask** [Layr-Labs/eigenda-proxy#72]
Using redis would allow us to ensure that data isn't deleted when the instance is torn down. This will be especially useful for debugging / feedback cycles when engineering against a live rollup. Otherwise we'll have to reinstate the entire rollup if the proxy instance is terminated.

**Comment by samlaf** [comment]
@epociask this was my point. You added redis as a cache layer. But here's it's suggesting to add it as a replacement for memstore right? Why this separation between backends that store with Keys vs those that don't?

**Comment by epociask** [comment]
@samlaf this was an old issue filed before we introduced these newer abstractions. Technically we can achieve the same effect now by using a cache target with S3 for a memstore backend.

**Comment by epociask** [comment]
closed by https://github.com/Layr-Labs/eigenda-proxy/pull/111
